INSERT INTO `rex_metainfo_field` (`title`, `name`, `priority`, `attributes`, `type_id`, `default`, `params`, `validate`, `callback`, `restrictions`, `createuser`, `createdate`, `updateuser`, `updatedate`)
VALUES
  ('Beschreibung','med_description',1,'',1,'','','','','','Administrator','2018-09-10 12:00:00','Administrator','2018-09-10 12:00:00');

INSERT INTO `rex_yform_table` (`status`, `table_name`, `name`, `description`, `list_amount`, `list_sortfield`, `list_sortorder`, `prio`, `search`, `hidden`, `export`, `import`, `mass_deletion`, `mass_edit`, `history`)
VALUES
  (1,'rex_ycom_comment','Community Kommentare','Ermöglicht Kommentare auf allen Artikeln, wenn man eingeloggt ist.',50,'id','DESC',3,1,0,0,0,1,0,0),
  (1,'rex_blog','Blog','Blog',50,'id','ASC',5,1,1,1,1,1,0,0);

INSERT INTO `rex_yform_field` (`table_name`, `prio`, `type_id`, `type_name`, `list_hidden`, `search`, `name`, `label`, `not_required`, `options`, `multiple`, `default`, `size`, `only_empty`, `message`, `table`, `hashname`, `password_hash`, `no_db`, `password_label`, `field`, `type`, `empty_value`, `empty_option`, `max_size`, `types`, `fields`, `position`, `address`, `width`, `height`, `attributes`, `preview`, `category`, `values`, `format`, `show_value`, `html`, `notice`, `regex`, `pattern`, `current_date`, `widget`, `query`, `year_start`, `year_end`, `rules`, `nonce_key`, `nonce_referer`, `sizes`, `messages`, `rules_message`, `script`)
VALUES
  ('rex_ycom_comment',1,'value','textarea',0,1,'comment','Kommentar','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',2,'validate','empty',1,0,'comment','','','','','','','','Bitte Kommentar eingeben','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',4,'value','be_manager_relation',0,1,'user_id','User','','','','','','','','rex_ycom_user','','','','','email','0','','0','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',5,'value','checkbox',0,1,'status','online','','','','0','','','','','','','','','','','','','','','','','','','','','','','0,1','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',3,'value','be_link',0,1,'article','Artikel','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',6,'value','datestamp',1,1,'stamp','mysql','','','','','','0','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',1,'value','datestamp',0,1,'datestamp','Datum','','','','','','0','','','','','','','','','','','','','','','','','','','','','','Y-m-d H:i:s','','','','','','','','','','','','','','','','',''),
  ('rex_blog',2,'value','text',0,1,'title','Titel','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"Titel des Beitrags\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',4,'value','text',0,1,'author','Autor','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"Autor des Beitrags\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',6,'value','textarea',1,1,'contribution','Beitrag','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"Text\",\"class\":\"form-control cke5-editor\",\"data-profile\":\"default\",\"data-lang\":\"de\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',7,'value','be_media',1,1,'headerimage','Titel-Grafik','','','0','','','','','','','','','','','','','','','jpg,png,gif','','','','','','','1','13','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',8,'value','be_media',1,1,'images','Fotos','','','1','','','','','','','','','','','','','','','jpg,png,gif','','','','','','','1','4','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',9,'value','text',1,1,'youtube','YouTube Video einbetten','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"embed code\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',5,'value','text',1,1,'contact','Kontakt zum Autor','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"kontakt.autor@email.de\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',7,'value','text',0,1,'vorname','Vorname','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"Vorname\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',8,'value','text',0,1,'nachname','Nachname','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"Nachname\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',9,'value','text',0,1,'emailadresse','E-Mail','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"E-Mail-Adresse\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',10,'value','text',0,1,'webseite','Webseite','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"Webseite\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',11,'value','text',1,1,'blogartikel_id','Blog-Artikel-ID','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',3,'value','text',1,1,'description','Beschreibung','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"description in Metatags\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',10,'value','select',0,1,'comments','Kommentare','','nein=0,ja=1','0','0','1','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_blog',11,'value','select',0,0,'status','translate:status','','offline=0,online=1,Arbeitsversion=2','0','0','1','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
  
  INSERT INTO `rex_url_generate` (`article_id`, `clang_id`, `url`, `table`, `table_parameters`, `relation_table`, `relation_table_parameters`, `relation_insert`, `createdate`, `createuser`, `updatedate`, `updateuser` )
VALUES
  ('1','1','','1_xxx_rex_blog','{"1_xxx_rex_blog_field_1":"title","1_xxx_rex_blog_field_2":"","1_xxx_rex_blog_field_3":"","1_xxx_rex_blog_id":"id","1_xxx_rex_blog_clang_id":"","1_xxx_rex_blog_restriction_field":"","1_xxx_rex_blog_restriction_operator":"=","1_xxx_rex_blog_restriction_value":"","1_xxx_rex_blog_url_param_key":"","1_xxx_rex_blog_seo_title":"title","1_xxx_rex_blog_seo_description":"description","1_xxx_rex_blog_seo_image":"","1_xxx_rex_blog_sitemap_add":"1","1_xxx_rex_blog_sitemap_frequency":"always","1_xxx_rex_blog_sitemap_priority":"1.0","1_xxx_rex_blog_sitemap_lastmod":"datestamp","1_xxx_rex_blog_path_names":"","1_xxx_rex_blog_path_categories":"0","1_xxx_rex_blog_relation_field":""}','','[]','before','','Blog-AddOn','','Blog-Addon');
