INSERT INTO `rex_yform_field` (`table_name`, `prio`, `type_id`, `type_name`, `list_hidden`, `search`, `name`, `label`, `not_required`, `options`, `multiple`, `default`, `size`, `only_empty`, `message`, `table`, `hashname`, `password_hash`, `no_db`, `password_label`, `field`, `type`, `empty_value`, `empty_option`, `max_size`, `types`, `fields`, `position`, `address`, `width`, `height`, `attributes`, `preview`, `category`, `values`, `format`, `show_value`, `html`, `notice`, `regex`, `pattern`, `current_date`, `widget`, `query`, `year_start`, `year_end`, `rules`, `nonce_key`, `nonce_referer`, `sizes`, `messages`, `rules_message`, `script`)
VALUES
  ('rex_ycom_comment',1,'value','textarea',0,1,'comment','Kommentar','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',2,'validate','empty',1,0,'comment','','','','','','','','Bitte Kommentar eingeben','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',4,'value','be_manager_relation',0,1,'user_id','User','','','','','','','','rex_ycom_user','','','','','email','0','','0','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',5,'value','checkbox',0,1,'status','online','','','','0','','','','','','','','','','','','','','','','','','','','','','','0,1','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',3,'value','be_link',0,1,'article','Artikel','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',6,'value','datestamp',1,1,'stamp','mysql','','','','','','0','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',7,'value','text',0,1,'vorname','Vorname','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"Vorname\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',8,'value','text',0,1,'nachname','Nachname','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"Nachname\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',9,'value','text',0,1,'emailadresse','E-Mail','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"E-Mail-Adresse\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',10,'value','text',0,1,'webseite','Webseite','','','','','','','','','','','','','','','','','','','','','','','','{\"placeholder\":\"Webseite\"}','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_ycom_comment',11,'value','text',1,1,'blogartikel_id','Blog-Artikel-ID','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
